# Generated by Django 3.1.1 on 2020-11-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microDonation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='charityorg',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
